// flow-typed signature: d8c6cd05ddaf4a40e7b06d2e3256c12e
// flow-typed version: <<STUB>>/vcards-js_v^2.8.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vcards-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vcards-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vcards-js/lib/vCardFormatter' {
  declare module.exports: any;
}

declare module 'vcards-js/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vcards-js/index' {
  declare module.exports: $Exports<'vcards-js'>;
}
declare module 'vcards-js/index.js' {
  declare module.exports: $Exports<'vcards-js'>;
}
declare module 'vcards-js/lib/vCardFormatter.js' {
  declare module.exports: $Exports<'vcards-js/lib/vCardFormatter'>;
}
declare module 'vcards-js/test/tests.js' {
  declare module.exports: $Exports<'vcards-js/test/tests'>;
}
